apiVersion: v1
kind: Pod
metadata:
  name: nopvcpod
spec:
  containers:
    - name: nginx
      image: nginx
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: notexisting-pvc
