apiVersion: v1
kind: Pod
metadata:
  name: hostpath-sample
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "15000"]

    volumeMounts:
    - name: host-vol
      mountPath: /data

  volumes:
  - name: host-vol
    hostPath:
      path: /tmp/host-data
      type: DirectoryOrCreate
