apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
  namespace: sample

spec:
  containers:
  - name: test-cont
    image: busybox
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: samplestorage

  volumes:
  - name: samplestorage
    persistentVolumeClaim:
      claimName: pvc-hvy
