apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: springapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springc
          image: abhinavbabu33/spring:v1
          envFrom:
            - configMapRef:
                name: config-app
            - secretRef:
                name: spring-secret
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
