apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-notin-demo
  namespace: scheduling-demo
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: NotIn
            values:
            - dev
